# Generated by Django 6.1.1 on 2026-09-29 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_event_all_day_eventimport_event_source_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text="Untick to remove this person's access.", verbose_name='can sign in')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff member',
                'ordering': ['email'],
            },
        ),
    ]
