# Generated by Django 6.1.1 on 2026-09-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='description_ms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='title_ms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='title_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='body_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='body_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_ms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption_ms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
