# Generated by Django 6.1.1 on 2026-09-29 02:56

from django.db import migrations, models


def existing_subscribers_signed_up_in_english(apps, schema_editor):
    # Everyone who signed up before this change used the English-only site.
    apps.get_model("portal", "Subscriber").objects.update(language="en")


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_existing_text_is_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='language',
            field=models.CharField(choices=[('ta', 'தமிழ்'), ('ms', 'Bahasa Melayu'), ('en', 'English')], default='ta', help_text='Emails are sent in this language: the one the parent used to sign up.', max_length=5, verbose_name='email language'),
        ),
        migrations.RunPython(existing_subscribers_signed_up_in_english, migrations.RunPython.noop),
    ]
