# Generated by Django 6.1.1 on 2026-09-29 02:57

from django.db import migrations, models


def earlier_imports_were_english(apps, schema_editor):
    apps.get_model("portal", "EventImport").objects.update(language="en")


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_subscriber_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimport',
            name='language',
            field=models.CharField(choices=[('ta', 'தமிழ்'), ('ms', 'Bahasa Melayu'), ('en', 'English')], default='ta', help_text='The language the spreadsheet is written in; its text is saved under it.', max_length=5),
        ),
        migrations.RunPython(earlier_imports_were_english, migrations.RunPython.noop),
    ]
