# Generated by Django 6.1.1 on 2026-09-29 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_import_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('x', 'X'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(help_text='The full address, e.g. https://www.facebook.com/yourschool', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='link')),
                ('label', models.CharField(blank=True, help_text='Optional name to show instead of the platform, e.g. “PIBG Facebook group”. Required for “Other”.', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
            ],
            options={
                'verbose_name': 'social media link',
                'ordering': ['order', 'platform', 'pk'],
            },
        ),
    ]
