# Generated by Django 6.1.1 on 2026-10-08 02:34

import django.core.validators
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ta', models.CharField(max_length=200, null=True)),
                ('title_ms', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(blank=True, help_text='Optional, one line, e.g. “Return by Friday 17 October”.', max_length=200)),
                ('note_ta', models.CharField(blank=True, help_text='Optional, one line, e.g. “Return by Friday 17 October”.', max_length=200, null=True)),
                ('note_ms', models.CharField(blank=True, help_text='Optional, one line, e.g. “Return by Friday 17 October”.', max_length=200, null=True)),
                ('note_en', models.CharField(blank=True, help_text='Optional, one line, e.g. “Return by Friday 17 October”.', max_length=200, null=True)),
                ('group', models.CharField(choices=[('circular', 'Circulars'), ('form', 'Forms'), ('list', 'Timetables and lists'), ('school', 'School documents')], max_length=20)),
                ('file', models.FileField(help_text='PDF, Word, Excel, PowerPoint, JPG or PNG, up to 10 MB.', upload_to='documents/%Y/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png'], message='Upload a PDF, Word, Excel, PowerPoint, JPG or PNG file.'), portal.models.validate_document_size])),
                ('remove_after', models.DateField(blank=True, help_text='It leaves the Documents page after this day. Leave empty to keep it there.', null=True, verbose_name='remove after')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'ordering': ['-added_at', '-pk'],
            },
        ),
    ]
