# Generated by Django 6.1.1 on 2026-10-08 03:48

import django.core.validators
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='e.g. 03-8723 1234', max_length=30, validators=[portal.models.validate_malaysian_number])),
                ('whatsapp', models.CharField(blank=True, help_text="The office's WhatsApp number, e.g. 012-345 6789.", max_length=30, validators=[portal.models.validate_malaysian_number], verbose_name='WhatsApp number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='The postal address, as on a letter.')),
                ('hours', models.TextField(blank=True, help_text='e.g. Monday to Friday, 7.30 am to 1.00 pm', verbose_name='office hours')),
                ('hours_ta', models.TextField(blank=True, help_text='e.g. Monday to Friday, 7.30 am to 1.00 pm', null=True, verbose_name='office hours')),
                ('hours_ms', models.TextField(blank=True, help_text='e.g. Monday to Friday, 7.30 am to 1.00 pm', null=True, verbose_name='office hours')),
                ('hours_en', models.TextField(blank=True, help_text='e.g. Monday to Friday, 7.30 am to 1.00 pm', null=True, verbose_name='office hours')),
                ('map_url', models.URLField(blank=True, help_text="Optional. Paste the school's Google Maps link so the button opens the exact pin.", validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Google Maps link')),
            ],
            options={
                'verbose_name': 'contact details',
                'verbose_name_plural': 'contact details',
            },
        ),
    ]
