# Generated by Django 6.1.1 on 2026-10-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_schoolcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('event', 'Event'), ('holiday', 'Holiday'), ('exam', 'Exam'), ('pibg', 'PIBG'), ('sports', 'Sports'), ('celebration', 'Celebration')], default='event', help_text='Holidays and exams stand out on the Events page.', max_length=20, verbose_name='type'),
        ),
    ]
