# Generated by Django 6.1.1 on 2026-10-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_event_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
