# Generated by Django 6.1.1 on 2026-10-09 02:19

import django.core.validators
import django.utils.timezone
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_event_reminded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='One line, e.g. “School is closed today because of flooding.”', max_length=200)),
                ('message_ta', models.CharField(help_text='One line, e.g. “School is closed today because of flooding.”', max_length=200, null=True)),
                ('message_ms', models.CharField(help_text='One line, e.g. “School is closed today because of flooding.”', max_length=200, null=True)),
                ('message_en', models.CharField(help_text='One line, e.g. “School is closed today because of flooding.”', max_length=200, null=True)),
                ('link', models.URLField(blank=True, help_text='Optional. A page with more details, e.g. a news post or a document.', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='show from')),
                ('ends_at', models.DateTimeField(default=portal.models.default_end, help_text='It disappears by itself after this. Set from 6 pm, it defaults to the end of tomorrow; check it fits your notice.', verbose_name='show until')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
            ],
            options={
                'verbose_name': 'urgent notice',
                'ordering': ['-starts_at'],
            },
        ),
    ]
