# Generated by Django 6.1.1 on 2026-10-09 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_urgentnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. “1st place, district Tamil essay competition”', max_length=200)),
                ('title_ta', models.CharField(help_text='e.g. “1st place, district Tamil essay competition”', max_length=200, null=True)),
                ('title_ms', models.CharField(help_text='e.g. “1st place, district Tamil essay competition”', max_length=200, null=True)),
                ('title_en', models.CharField(help_text='e.g. “1st place, district Tamil essay competition”', max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ta', models.TextField(blank=True, null=True)),
                ('description_ms', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('sports', 'Sports'), ('arts', 'Arts and culture'), ('tamil', 'Tamil language'), ('other', 'Other')], max_length=20)),
                ('level', models.CharField(choices=[('school', 'School'), ('district', 'District'), ('state', 'State'), ('national', 'National'), ('international', 'International')], max_length=20)),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AchievementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='achievements/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('caption_ta', models.CharField(blank=True, max_length=200, null=True)),
                ('caption_ms', models.CharField(blank=True, max_length=200, null=True)),
                ('caption_en', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portal.achievement')),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AchievementPupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='As on the certificate.', max_length=100)),
                ('class_name', models.CharField(blank=True, help_text='e.g. 5 Mutiara', max_length=30, verbose_name='class')),
                ('consent', models.BooleanField(default=False, help_text="Tick only if the parents agreed to their child's name and photo being shown.", verbose_name='parents agreed')),
                ('show_full_name', models.BooleanField(default=False, help_text='Otherwise only the first name and an initial are shown.')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupils', to='portal.achievement')),
            ],
            options={
                'verbose_name': 'pupil',
                'ordering': ['pk'],
            },
        ),
    ]
