# Generated by Django 6.1.1 on 2026-10-10 12:54

import django.core.validators
import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pibg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, help_text="The committee's term, e.g. 2026/2027.", max_length=20)),
                ('about', models.TextField(blank=True, help_text='What PIBG does, the yearly fee and how to pay, and how to volunteer.', verbose_name='about and how to take part')),
                ('about_ta', models.TextField(blank=True, help_text='What PIBG does, the yearly fee and how to pay, and how to volunteer.', null=True, verbose_name='about and how to take part')),
                ('about_ms', models.TextField(blank=True, help_text='What PIBG does, the yearly fee and how to pay, and how to volunteer.', null=True, verbose_name='about and how to take part')),
                ('about_en', models.TextField(blank=True, help_text='What PIBG does, the yearly fee and how to pay, and how to volunteer.', null=True, verbose_name='about and how to take part')),
                ('phone', models.CharField(blank=True, help_text='The shared PIBG number, e.g. 012-345 6789. Shown publicly.', max_length=30, validators=[portal.models.validate_malaysian_number])),
                ('email', models.EmailField(blank=True, help_text='The shared PIBG email. Shown publicly.', max_length=254)),
                ('whatsapp_group', models.URLField(blank=True, help_text='The PIBG WhatsApp group invite link, e.g. https://chat.whatsapp.com/…', validators=[django.core.validators.URLValidator(schemes=['https'])], verbose_name='WhatsApp group link')),
            ],
            options={
                'verbose_name': 'PIBG',
                'verbose_name_plural': 'PIBG',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.CharField(choices=[('circular', 'Circulars'), ('form', 'Forms'), ('list', 'Timetables and lists'), ('pibg', 'PIBG'), ('school', 'School documents')], max_length=20),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('chair', 'Chairperson'), ('vice_chair', 'Vice-chairperson'), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant secretary'), ('treasurer', 'Treasurer'), ('assistant_treasurer', 'Assistant treasurer'), ('auditor', 'Auditor'), ('advisor', 'Advisor'), ('member', 'Committee member')], default='member', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Orders people with the same role; lower numbers come first.')),
                ('pibg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='portal.pibg')),
            ],
            options={
                'verbose_name': 'committee member',
                'ordering': ['pk'],
            },
        ),
    ]
